/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/saldanhaUnido.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/saldanhaUnido.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-2.123, -0.3, -2.823]} scale={[1, 1, 3]}>
        <mesh geometry={nodes.Plane001_1.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Plane001_2.geometry} material={materials.Material} />
        <mesh geometry={nodes.Plane001_3.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Plane001_4.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Plane001_5.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Plane001_6.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Plane001_7.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Plane001_8.geometry} material={materials['Material.008']} />
      </group>
    </group>
  )
}

useGLTF.preload('/saldanhaUnido.glb')
